const crypto = require("crypto");
const { normalizeNorthAmericanE164 } = require("./canadianPhoneNumber");

const CLOSED_SIGNUP_STATUSES = ["archived", "abandoned_archived", "superseded_duplicate", "rejected", "decommissioned"];
function isClosedSignup(record = {}) {
  return Boolean(record.archivedAt || record.rejectedAt || CLOSED_SIGNUP_STATUSES.includes(String(record.status || "").trim().toLowerCase()));
}

// Generated by the server, never accepted as a client-selected tenant ID.
// Renames/contact changes require an authenticated migration, not a guess.
function signupBusinessKey(record = {}) {
  const name = String(record.businessName || record.business?.name || record.businessProfile?.businessName || "").normalize("NFKC").replace(/\s+/g, " ").trim().toLowerCase();
  const email = String(record.ownerEmail || record.owner?.email || record.setupDetails?.ownerEmail || "").trim().toLowerCase();
  const phone = normalizeNorthAmericanE164(record.ownerPhone || record.owner?.phone || record.setupDetails?.ownerPhone);
  if (!name || !email || !phone) return "";
  return crypto.createHash("sha256").update(`signup-business:v1\0${email}\0${phone}\0${name}`).digest("hex");
}

function assertSignupOpen(record) {
  if (!isClosedSignup(record)) return;
  const error = new Error("This signup is closed. Delayed updates cannot reopen it.");
  error.code = "SIGNUP_CLOSED";
  error.statusCode = 409;
  throw error;
}

module.exports = { CLOSED_SIGNUP_STATUSES, isClosedSignup, signupBusinessKey, assertSignupOpen };
