import { timsElectricalRecordedTranscripts } from "./timsElectricalRecordedTranscripts";

export const timsElectricalCompany = {
  name: "Tim's Electrical",
  privateNotice:
    "Demonstration prepared by My AI PA. All callers, addresses, messages, and job details shown here are simulated.",
};

export const timsElectricalFlowCards = [
  {
    icon: "bolt",
    title: "New installations",
    text: "Capture the project, property address, timing, and callback details without promising a price or appointment.",
  },
  {
    icon: "wrench",
    title: "Repair inquiries",
    text: "Organize the symptoms and affected area while leaving diagnosis and repair advice to a qualified electrician.",
  },
  {
    icon: "document",
    title: "Maintenance questions",
    text: "Record what the caller wants inspected, their preferred timing, and any helpful site-access notes.",
  },
  {
    icon: "message",
    title: "Follow-up concerns",
    text: "Give existing customers a calm way to document an unresolved concern and request a team callback.",
  },
];

export const timsElectricalKnowledge = [
  {
    label: "Call types",
    value: "The demonstration handles new installation, repair, maintenance, quote, and follow-up inquiries.",
  },
  {
    label: "Useful job details",
    value: "It can collect the caller's name, callback number, service address, city, issue, preferred timing, and safety indicators.",
  },
  {
    label: "Two-sided follow-up",
    value: "The owner receives an organized lead summary and the caller receives a concise confirmation when texting is enabled and consented.",
  },
  {
    label: "Optional price qualification",
    value: "A business-approved service-call fee can be shared before handoff, followed by a simple choice to continue. No price is invented by the assistant.",
  },
];

export const timsElectricalConfirmations = [
  {
    label: "Price or estimate",
    text: "Only a fee explicitly approved by the electrical business may be shared. All other pricing and estimate terms require team confirmation.",
  },
  {
    label: "Appointment or arrival time",
    text: "The receptionist may record preferences but must not promise scheduling or response times.",
  },
  {
    label: "Service area and availability",
    text: "The team must confirm that it serves the address and can accept the requested work.",
  },
];

export const timsElectricalBoundaries = [
  "Never diagnose an electrical problem or instruct a caller to inspect dangerous equipment.",
  "Never guarantee a price, appointment, response time, warranty, licence, certification, or technician availability.",
  "Stop ordinary intake when smoke, fire, sparks, burning wiring, or immediate danger is reported.",
  "Read back critical phone and address details before preparing the handoff.",
  "Describe message delivery truthfully and only after the delivery result is confirmed.",
];

// Every visible representation of a scenario is derived from this capture model.
// `capturedAt` is the first transcript-line count after which a value is known.
const scenarioDetails = {
  "new-installation": {
    callerName: "Brian Smith",
    callbackNumber: "905-555-1234",
    details: [
      { label: "Intent", value: "New installation", capturedAt: 2 },
      { label: "Customer", value: "Brian Smith", capturedAt: 4 },
      { label: "Callback", value: "905-555-1234", capturedAt: 8 },
      { label: "Work requested", value: "Hot tub wiring", capturedAt: 2 },
      { label: "Job address", value: "23 Robb Street, Hamilton", capturedAt: 6 },
      { label: "Preferred callback", value: "After 5 p.m.", capturedAt: 8 },
      { label: "Interest / next action", value: "Quote follow-up requested", capturedAt: 11 },
      { label: "Priority", value: "Installation opportunity", capturedAt: 2 },
      { label: "Route", value: "Electrical team — quote follow-up", capturedAt: 11 },
    ],
    missing: ["Preferred start date", "Site-access notes"],
    ownerHeading: "NEW INSTALLATION",
    ownerPoints: ["Brian Smith", "905-555-1234", "Hot tub wiring", "23 Robb Street, Hamilton", "Preferred callback: after 5 p.m.", "Next action: quote follow-up"],
    customerPoints: ["Thanks for calling Tim's Electrical.", "Request received: hot tub wiring", "Location: 23 Robb Street, Hamilton", "Next step: the team will follow up to discuss the details and timing."],
  },
  "repair-request": {
    callerName: "Maya Chen",
    callbackNumber: "905-555-0168",
    details: [
      { label: "Intent", value: "Repair request", capturedAt: 2 },
      { label: "Customer", value: "Maya Chen", capturedAt: 6 },
      { label: "Callback", value: "905-555-0168", capturedAt: 10 },
      { label: "Problem", value: "Kitchen outlet has no power", capturedAt: 4 },
      { label: "Job address", value: "18 Lake Avenue, Grimsby", capturedAt: 8 },
      { label: "Preferred callback", value: "Mornings", capturedAt: 10 },
      { label: "Route", value: "Electrical team — repair review", capturedAt: 11 },
    ],
    missing: [],
    ownerHeading: "REPAIR REQUEST",
    ownerPoints: ["Maya Chen", "905-555-0168", "Kitchen outlet has no power", "18 Lake Avenue, Grimsby", "Preferred callback: mornings", "Next action: repair review"],
    customerPoints: ["Thanks for calling Tim's Electrical.", "Repair request received: kitchen outlet with no power", "Location: 18 Lake Avenue, Grimsby", "Next step: the team will review the service details and follow up."],
  },
  maintenance: {
    callerName: "Daniel Ortiz",
    callbackNumber: "905-555-0144",
    details: [
      { label: "Intent", value: "Maintenance", capturedAt: 2 },
      { label: "Customer", value: "Daniel Ortiz", capturedAt: 6 },
      { label: "Callback", value: "905-555-0144", capturedAt: 10 },
      { label: "Service requested", value: "Preventive electrical inspection", capturedAt: 2 },
      { label: "Property", value: "Older home", capturedAt: 2 },
      { label: "Job address", value: "44 Maple Drive, Stoney Creek", capturedAt: 8 },
      { label: "Preferred callback", value: "Weekday afternoons", capturedAt: 10 },
      { label: "Route", value: "Electrical team — maintenance review", capturedAt: 11 },
    ],
    missing: [],
    ownerHeading: "MAINTENANCE",
    ownerPoints: ["Daniel Ortiz", "905-555-0144", "Preventive electrical inspection", "44 Maple Drive, Stoney Creek", "Preferred callback: weekday afternoons", "Next action: maintenance review"],
    customerPoints: ["Thanks for calling Tim's Electrical.", "Maintenance request received: preventive electrical inspection", "Location: 44 Maple Drive, Stoney Creek", "Next step: the team will confirm scope, availability and pricing."],
  },
  "unresolved-concern": {
    callerName: "Aisha Patel",
    callbackNumber: "905-555-0171",
    details: [
      { label: "Intent", value: "Talk to the team", capturedAt: 2 },
      { label: "Customer type", value: "Existing customer", capturedAt: 2 },
      { label: "Customer", value: "Aisha Patel", capturedAt: 6 },
      { label: "Callback", value: "905-555-0171", capturedAt: 10 },
      { label: "Reason", value: "Update on flickering hallway light", capturedAt: 4 },
      { label: "Service address", value: "71 King Street, Hamilton", capturedAt: 8 },
      { label: "Preferred callback", value: "Evenings", capturedAt: 10 },
      { label: "Route", value: "Electrical team — private follow-up", capturedAt: 11 },
    ],
    missing: [],
    ownerHeading: "FOLLOW-UP REQUEST",
    ownerPoints: ["Aisha Patel", "905-555-0171", "Update on flickering hallway light", "71 King Street, Hamilton", "Preferred callback: evenings", "Next action: team callback"],
    customerPoints: ["Thanks for calling Tim's Electrical.", "Your request for an update was received.", "Location: 71 King Street, Hamilton", "Next step: the team will review the details and follow up."],
  },
  "urgent-outage": {
    callerName: "Noah Wilson",
    callbackNumber: "905-555-0109",
    details: [
      { label: "Intent", value: "Urgent issue", capturedAt: 2 },
      { label: "Customer", value: "Noah Wilson", capturedAt: 6 },
      { label: "Callback", value: "905-555-0109", capturedAt: 10 },
      { label: "Problem", value: "Complete home outage", capturedAt: 2 },
      { label: "Safety check", value: "No immediate-danger indicators reported", capturedAt: 4 },
      { label: "Location", value: "9 Orchard Lane, Grimsby", capturedAt: 8 },
      { label: "Availability", value: "Available now", capturedAt: 10 },
      { label: "Route", value: "Electrical team — urgent review", capturedAt: 11 },
    ],
    missing: [],
    ownerHeading: "PRIORITY CALLBACK",
    ownerPoints: ["Noah Wilson", "905-555-0109", "Complete home outage", "9 Orchard Lane, Grimsby", "No immediate-danger indicators reported", "Available now", "Next action: urgent review — not dispatch"],
    customerPoints: ["Thanks for calling Tim's Electrical.", "Urgent outage request received.", "Location: 9 Orchard Lane, Grimsby", "Next step: the team must review the details; this is not a dispatch confirmation."],
  },
  "safety-redirect": {
    callerName: "Simulated caller",
    callbackNumber: "",
    details: [
      { label: "Intent", value: "Immediate-danger report", capturedAt: 2 },
      { label: "Safety indicators", value: "Sparks and smoke", capturedAt: 2 },
      { label: "Action", value: "Ordinary intake stopped; caller directed to 911", capturedAt: 3 },
      { label: "Route", value: "911 — ordinary intake stopped", capturedAt: 3 },
    ],
    missing: [],
    ownerHeading: "SAFETY EVENT",
    ownerPoints: ["Sparks and smoke reported", "Ordinary service intake stopped", "Caller directed to leave danger and call 911"],
    customerPoints: ["No routine confirmation text is prepared during an emergency redirect.", "The caller was directed to leave danger and call 911."],
  },
};

export const timsElectricalScenarios = [
  {
    id: "new-installation",
    shortLabel: "New installation",
    title: "Homeowner needs a hot tub wired",
    intent: "New installation",
    priority: "Installation opportunity",
    route: "Electrical team · quote follow-up",
    stages: ["Service identified", "Job details collected", "Timing confirmed", "Texts prepared"],
    transcript: [
      { speaker: "assistant", text: "Hello are you looking for a new installation, repair or maintenance today?" },
      { speaker: "caller", text: "I need someone to wire up my hot tub as a new installation." },
      { speaker: "assistant", text: "Can I get your first name?" },
      { speaker: "caller", text: "Brian Smith." },
      { speaker: "assistant", text: "What's the address where the work needs to be completed?" },
      { speaker: "caller", text: "23 Robb Street in Hamilton." },
      { speaker: "assistant", text: "What is the best phone number to reach you at?" },
      { speaker: "caller", text: "Nine oh five, five five five, one two three four." },
      { speaker: "assistant", text: "Repeating that back, nine oh five, five five five, one two three four. Is that correct?" },
      { speaker: "caller", text: "Yes." },
      { speaker: "assistant", text: "What's the best time to reach you in case we miss you on the callback?" },
      { speaker: "caller", text: "After five PM is best." },
      { speaker: "assistant", text: "To confirm, that's 23 Robb Street in Hamilton for hot tub wiring, and after five PM is your best callback time. I have the details ready for the team. Thanks for calling." },
    ],
    collected: ["Brian Smith", "905-555-1234", "23 Robb Street · Hamilton", "New hot tub wiring", "Callback after 5 p.m."],
    missing: ["Preferred start date", "Site-access notes"],
    summary: "Brian needs a licensed electrician to wire a newly installed hot tub at 23 Robb Street in Hamilton and prefers a callback after 5 p.m.",
    ownerText: "NEW INSTALLATION · Brian Smith · 905-555-1234 · New hot tub wiring · 23 Robb Street, Hamilton · Callback after 5 p.m. · Pricing and scheduling require confirmation.",
    customerText: "Thanks for calling Tim's Electrical. We received your hot tub wiring request. The team will follow up to discuss the details and next steps. Have a great day!",
  },
  {
    id: "repair-request",
    shortLabel: "Repair request",
    title: "Homeowner reports an outlet stopped working",
    intent: "Electrical repair inquiry",
    priority: "Standard service inquiry",
    route: "Electrical team · repair review",
    stages: ["Problem identified", "Safety checked", "Contact confirmed", "Texts prepared"],
    transcript: [
      { speaker: "assistant", text: "Please describe what is happening." },
      { speaker: "caller", text: "Two kitchen outlets stopped working this afternoon." },
      { speaker: "assistant", text: "Is there smoke, sparking, a burning smell, heat, or immediate danger?" },
      { speaker: "caller", text: "No. The outlets just have no power." },
      { speaker: "assistant", text: "Thank you. What's your name and the service address?" },
      { speaker: "caller", text: "Maya Chen, 18 King Street in Grimsby." },
      { speaker: "assistant", text: "What is the best callback number?" },
      { speaker: "caller", text: "905-555-0188." },
      { speaker: "assistant", text: "I'll prepare the repair request for the team. They will confirm whether the address and requested work can be served." },
    ],
    collected: ["Maya Chen", "905-555-0168", "18 Lake Avenue · Grimsby", "Kitchen outlet stopped working", "No immediate-danger indicators reported", "Mornings preferred"],
    missing: [],
    summary: "Maya reports that a kitchen outlet stopped working yesterday at 18 Lake Avenue in Grimsby. She reports no smoke, sparks, heat, burning smell, or immediate danger and prefers mornings.",
    ownerText: "REPAIR REQUEST · Maya Chen · 905-555-0168 · Kitchen outlet stopped working yesterday · 18 Lake Avenue, Grimsby · No immediate-danger indicators reported · Mornings preferred.",
    customerText: "Thanks for calling Tim's Electrical. We received your outlet repair request. The team will follow up after reviewing the service details.",
  },
  {
    id: "maintenance",
    shortLabel: "Maintenance",
    title: "Customer asks about an electrical inspection",
    intent: "Maintenance inquiry",
    priority: "Standard service inquiry",
    route: "Electrical team · maintenance review",
    stages: ["Request identified", "Property collected", "Timing collected", "Texts prepared"],
    transcript: [
      { speaker: "assistant", text: "What would you like the electrical team to inspect?" },
      { speaker: "caller", text: "I'd like someone to look over the panel in a house I recently bought." },
      { speaker: "assistant", text: "Are you experiencing smoke, sparks, a burning smell, heat, or an outage right now?" },
      { speaker: "caller", text: "No. This is preventive." },
      { speaker: "assistant", text: "May I get your name, callback number, and the property address?" },
      { speaker: "caller", text: "Jordan Lee, 905-555-0144, 72 Main Street in Hamilton." },
      { speaker: "assistant", text: "What callback time works best?" },
      { speaker: "caller", text: "Weekday mornings." },
      { speaker: "assistant", text: "I'll prepare the inspection inquiry. The team will confirm the scope, availability, and pricing." },
    ],
    collected: ["Daniel Ortiz", "905-555-0144", "44 Maple Drive · Stoney Creek", "Preventive electrical inspection", "Older home", "Weekday afternoons"],
    missing: [],
    summary: "Daniel is requesting a preventive electrical inspection for an older home at 44 Maple Drive in Stoney Creek and prefers weekday afternoons.",
    ownerText: "MAINTENANCE · Daniel Ortiz · 905-555-0144 · Preventive electrical inspection for an older home · 44 Maple Drive, Stoney Creek · Weekday afternoons.",
    customerText: "Thanks for calling Tim's Electrical. We received your panel-inspection inquiry. The team will follow up to confirm the scope, availability, and pricing.",
  },
  {
    id: "unresolved-concern",
    shortLabel: "Talk to the team",
    title: "Customer asks to discuss an unresolved concern",
    intent: "Existing-customer follow-up",
    priority: "Team callback requested",
    route: "Electrical team · private follow-up",
    stages: ["Customer identified", "Concern documented", "Next step requested", "Callback prepared"],
    transcript: [
      { speaker: "assistant", text: "I can document your concern and prepare a callback request for the team. What happened?" },
      { speaker: "caller", text: "I asked about a flickering hallway light last week and still need an update." },
      { speaker: "assistant", text: "Is there smoke, sparking, a burning smell, heat, or immediate danger now?" },
      { speaker: "caller", text: "No. I just want to know the next step." },
      { speaker: "assistant", text: "May I get your name, callback number, and service address?" },
      { speaker: "caller", text: "Priya Shah, 905-555-0177, 18 George Street." },
      { speaker: "assistant", text: "What would you like the team to do next?" },
      { speaker: "caller", text: "Please call me with an update. Evenings are best." },
      { speaker: "assistant", text: "I'll prepare that callback request without promising an outcome or response time." },
    ],
    collected: ["Aisha Patel", "905-555-0171", "71 King Street · Hamilton", "Existing customer", "Flickering hallway light follow-up", "Evening callback"],
    missing: [],
    summary: "Aisha is an existing customer requesting an evening callback about a flickering hallway light discussed the previous week at 71 King Street in Hamilton.",
    ownerText: "FOLLOW-UP REQUEST · Aisha Patel · 905-555-0171 · 71 King Street, Hamilton · Existing customer awaiting an update about a flickering hallway light · Evenings preferred.",
    customerText: "Thanks for calling Tim's Electrical. We recorded your request for an update and your evening callback preference. The team will review the details and follow up.",
  },
  {
    id: "urgent-outage",
    shortLabel: "Urgent issue",
    title: "Customer reports a complete home power outage",
    intent: "Urgent electrical inquiry",
    priority: "Priority callback",
    route: "Electrical team · urgent review",
    stages: ["Danger checked", "Impact confirmed", "Contact collected", "Priority summary ready"],
    transcript: [
      { speaker: "caller", text: "The whole house lost power, but the neighbours still have electricity." },
      { speaker: "assistant", text: "Is there smoke, fire, sparking, a burning smell, heat at the panel, or any immediate danger?" },
      { speaker: "caller", text: "No, none of those." },
      { speaker: "assistant", text: "I'll mark this as an urgent issue for review. What is your name and service address?" },
      { speaker: "caller", text: "Alex Martin, 91 Lake Street in Grimsby." },
      { speaker: "assistant", text: "What is the best callback number?" },
      { speaker: "caller", text: "905-555-0160." },
      { speaker: "assistant", text: "I'll prepare the urgent request. I cannot guarantee dispatch or a response time, and the electrical team must confirm the next step." },
    ],
    collected: ["Noah Wilson", "905-555-0109", "9 Orchard Lane · Grimsby", "Complete home outage", "Neighbours still have power", "No immediate-danger indicators reported", "Available now"],
    missing: [],
    summary: "PRIORITY — Noah reports a complete home outage at 9 Orchard Lane in Grimsby while neighbouring properties still have power. No immediate-danger indicators were reported, and he is available now.",
    ownerText: "PRIORITY CALLBACK · Noah Wilson · 905-555-0109 · Complete home outage · 9 Orchard Lane, Grimsby · Neighbours still have power · No immediate-danger indicators reported · Available now.",
    customerText: "Thanks for calling Tim's Electrical. We recorded your urgent power-outage request. This is not a dispatch confirmation; the team must review the details and contact you.",
  },
  {
    id: "safety-redirect",
    shortLabel: "Safety redirect",
    title: "Caller reports smoke and sparks",
    intent: "Immediate-danger report",
    priority: "Emergency redirect",
    route: "911 · ordinary intake stopped",
    stages: ["Danger detected", "Intake stopped", "Emergency direction given", "Minimal event stored"],
    transcript: [
      { speaker: "caller", text: "There are sparks and smoke coming from an outlet." },
      { speaker: "assistant", text: "Leave the area and call 911 now from a safe location. Do not touch the outlet or wait for a service callback. This demonstration cannot provide emergency dispatch." },
    ],
    collected: ["Electrical sparks", "Smoke", "Emergency redirect issued"],
    missing: [],
    summary: "The caller reported sparks and smoke. Ordinary intake stopped immediately and the caller was directed to leave danger and call 911.",
    ownerText: "SAFETY EVENT · Caller reported sparks and smoke · Ordinary service intake stopped · Caller directed to leave danger and call 911.",
    customerText: "No routine confirmation text is prepared during an emergency redirect. The caller was directed to leave danger and call 911.",
  },
].map((scenario) => {
  const model = scenarioDetails[scenario.id];
  const transcript = timsElectricalRecordedTranscripts[scenario.id] || scenario.transcript;
  const ownerTextLines = [model.ownerHeading, ...model.ownerPoints];
  return {
    ...scenario,
    businessName: timsElectricalCompany.name,
    callerName: model.callerName,
    callbackNumber: model.callbackNumber,
    details: model.details,
    transcript,
    collected: model.details.map(({ value }) => value),
    missing: model.missing,
    ownerTextLines,
    customerTextLines: model.customerPoints,
    ownerText: ownerTextLines.join(" · "),
    customerText: model.customerPoints.join(" "),
  };
});
