export const timsElectricalCompany = {
  name: "Tim's Electrical",
  privateNotice:
    "Demonstration prepared by My AI PA. All callers, addresses, messages, and job details shown here are simulated.",
};

export const timsElectricalFlowCards = [
  {
    icon: "bolt",
    title: "New installations",
    text: "Capture the project, property address, timing, and callback details without promising a price or appointment.",
  },
  {
    icon: "wrench",
    title: "Repair inquiries",
    text: "Organize the symptoms and affected area while leaving diagnosis and repair advice to a qualified electrician.",
  },
  {
    icon: "document",
    title: "Maintenance questions",
    text: "Record what the caller wants inspected, their preferred timing, and any helpful site-access notes.",
  },
  {
    icon: "message",
    title: "Follow-up concerns",
    text: "Give existing customers a calm way to document an unresolved concern and request a team callback.",
  },
];

export const timsElectricalKnowledge = [
  {
    label: "Call types",
    value: "The demonstration handles new installation, repair, maintenance, quote, and follow-up inquiries.",
  },
  {
    label: "Useful job details",
    value: "It can collect the caller's name, callback number, service address, city, issue, preferred timing, and safety indicators.",
  },
  {
    label: "Two-sided follow-up",
    value: "The owner receives an organized lead summary and the caller receives a concise confirmation when texting is enabled and consented.",
  },
];

export const timsElectricalConfirmations = [
  {
    label: "Price or estimate",
    text: "Exact pricing and estimate terms must be confirmed by the electrical business.",
  },
  {
    label: "Appointment or arrival time",
    text: "The receptionist may record preferences but must not promise scheduling or response times.",
  },
  {
    label: "Service area and availability",
    text: "The team must confirm that it serves the address and can accept the requested work.",
  },
];

export const timsElectricalBoundaries = [
  "Never diagnose an electrical problem or instruct a caller to inspect dangerous equipment.",
  "Never guarantee a price, appointment, response time, warranty, licence, certification, or technician availability.",
  "Stop ordinary intake when smoke, fire, sparks, burning wiring, or immediate danger is reported.",
  "Read back critical phone and address details before preparing the handoff.",
  "Describe message delivery truthfully and only after the delivery result is confirmed.",
];

export const timsElectricalScenarios = [
  {
    id: "new-installation",
    shortLabel: "New installation",
    title: "Homeowner needs a hot tub wired",
    intent: "New installation",
    priority: "Installation opportunity",
    route: "Electrical team · quote follow-up",
    stages: ["Service identified", "Job details collected", "Timing confirmed", "Texts prepared"],
    transcript: [
      { speaker: "assistant", text: "Thanks for calling Tim's Electrical. I'm the virtual receptionist. Are you calling about a new installation, a repair, or maintenance?" },
      { speaker: "caller", text: "I need someone to wire up a hot tub on my back deck." },
      { speaker: "assistant", text: "I can collect the project details for the team. May I get your name?" },
      { speaker: "caller", text: "Brian Smith." },
      { speaker: "assistant", text: "What's the address and city where the work is needed?" },
      { speaker: "caller", text: "63 York Street in St. Catharines." },
      { speaker: "assistant", text: "What is the best number and time for the team to call you?" },
      { speaker: "caller", text: "905-555-0123, after 5 p.m." },
      { speaker: "assistant", text: "I'll prepare those details for the team. They will confirm service availability, pricing, and scheduling with you." },
    ],
    collected: ["Brian Smith", "905-555-0123", "63 York Street · St. Catharines", "Hot tub wiring", "Callback after 5 p.m."],
    missing: ["Preferred project date", "Site-access notes"],
    summary: "Brian wants a quote for wiring a hot tub at 63 York Street in St. Catharines and prefers a callback after 5 p.m.",
    ownerText: "NEW INSTALLATION · Brian Smith · 905-555-0123 · Hot tub wiring · 63 York Street, St. Catharines · Callback after 5 p.m. · Pricing and schedule require confirmation.",
    customerText: "Thanks for calling Tim's Electrical. We received your hot tub wiring request. The team will follow up to confirm service availability, pricing, and scheduling.",
  },
  {
    id: "repair-request",
    shortLabel: "Repair request",
    title: "Homeowner reports an outlet stopped working",
    intent: "Electrical repair inquiry",
    priority: "Standard service inquiry",
    route: "Electrical team · repair review",
    stages: ["Problem identified", "Safety checked", "Contact confirmed", "Texts prepared"],
    transcript: [
      { speaker: "assistant", text: "Please describe what is happening." },
      { speaker: "caller", text: "Two kitchen outlets stopped working this afternoon." },
      { speaker: "assistant", text: "Is there smoke, sparking, a burning smell, heat, or immediate danger?" },
      { speaker: "caller", text: "No. The outlets just have no power." },
      { speaker: "assistant", text: "Thank you. What's your name and the service address?" },
      { speaker: "caller", text: "Maya Chen, 18 King Street in Grimsby." },
      { speaker: "assistant", text: "What is the best callback number?" },
      { speaker: "caller", text: "905-555-0188." },
      { speaker: "assistant", text: "I'll prepare the repair request for the team. They will confirm whether the address and requested work can be served." },
    ],
    collected: ["Maya Chen", "905-555-0188", "18 King Street · Grimsby", "Two kitchen outlets without power", "No smoke, sparks, heat, or burning smell"],
    missing: ["Preferred callback time"],
    summary: "Maya reports two kitchen outlets without power at 18 King Street in Grimsby. She reports no smoke, sparks, heat, or burning smell.",
    ownerText: "REPAIR REQUEST · Maya Chen · 905-555-0188 · Two kitchen outlets have no power · 18 King Street, Grimsby · No immediate-danger indicators reported.",
    customerText: "Thanks for calling Tim's Electrical. We received your outlet repair request. The team will follow up after reviewing the service details.",
  },
  {
    id: "maintenance",
    shortLabel: "Maintenance",
    title: "Customer asks about an electrical inspection",
    intent: "Maintenance inquiry",
    priority: "Standard service inquiry",
    route: "Electrical team · maintenance review",
    stages: ["Request identified", "Property collected", "Timing collected", "Texts prepared"],
    transcript: [
      { speaker: "assistant", text: "What would you like the electrical team to inspect?" },
      { speaker: "caller", text: "I'd like someone to look over the panel in a house I recently bought." },
      { speaker: "assistant", text: "Are you experiencing smoke, sparks, a burning smell, heat, or an outage right now?" },
      { speaker: "caller", text: "No. This is preventive." },
      { speaker: "assistant", text: "May I get your name, callback number, and the property address?" },
      { speaker: "caller", text: "Jordan Lee, 905-555-0144, 72 Main Street in Hamilton." },
      { speaker: "assistant", text: "What callback time works best?" },
      { speaker: "caller", text: "Weekday mornings." },
      { speaker: "assistant", text: "I'll prepare the inspection inquiry. The team will confirm the scope, availability, and pricing." },
    ],
    collected: ["Jordan Lee", "905-555-0144", "72 Main Street · Hamilton", "Preventive panel inspection", "Weekday mornings"],
    missing: ["Approximate panel age"],
    summary: "Jordan is requesting a preventive electrical-panel inspection at 72 Main Street in Hamilton and prefers weekday-morning contact.",
    ownerText: "MAINTENANCE · Jordan Lee · 905-555-0144 · Preventive panel inspection · 72 Main Street, Hamilton · Weekday mornings.",
    customerText: "Thanks for calling Tim's Electrical. We received your panel-inspection inquiry. The team will follow up to confirm the scope, availability, and pricing.",
  },
  {
    id: "unresolved-concern",
    shortLabel: "Talk to the team",
    title: "Customer asks to discuss an unresolved concern",
    intent: "Existing-customer follow-up",
    priority: "Team callback requested",
    route: "Electrical team · private follow-up",
    stages: ["Customer identified", "Concern documented", "Next step requested", "Callback prepared"],
    transcript: [
      { speaker: "assistant", text: "I can document your concern and prepare a callback request for the team. What happened?" },
      { speaker: "caller", text: "I asked about a flickering hallway light last week and still need an update." },
      { speaker: "assistant", text: "Is there smoke, sparking, a burning smell, heat, or immediate danger now?" },
      { speaker: "caller", text: "No. I just want to know the next step." },
      { speaker: "assistant", text: "May I get your name, callback number, and service address?" },
      { speaker: "caller", text: "Priya Shah, 905-555-0177, 18 George Street." },
      { speaker: "assistant", text: "What would you like the team to do next?" },
      { speaker: "caller", text: "Please call me with an update. Evenings are best." },
      { speaker: "assistant", text: "I'll prepare that callback request without promising an outcome or response time." },
    ],
    collected: ["Priya Shah", "905-555-0177", "18 George Street", "Flickering hallway light", "Previously discussed", "Evening callback"],
    missing: ["City"],
    summary: "Priya requests an evening callback about a flickering hallway light she says was previously discussed. No immediate-danger indicators were reported.",
    ownerText: "FOLLOW-UP REQUEST · Priya Shah · 905-555-0177 · 18 George Street · Flickering hallway light previously discussed · No immediate danger reported · Evenings preferred.",
    customerText: "Thanks for calling Tim's Electrical. We recorded your request for an update and your evening callback preference. The team will review the details and follow up.",
  },
  {
    id: "urgent-outage",
    shortLabel: "Urgent issue",
    title: "Customer reports a complete home power outage",
    intent: "Urgent electrical inquiry",
    priority: "Priority callback",
    route: "Electrical team · urgent review",
    stages: ["Danger checked", "Impact confirmed", "Contact collected", "Priority summary ready"],
    transcript: [
      { speaker: "caller", text: "The whole house lost power, but the neighbours still have electricity." },
      { speaker: "assistant", text: "Is there smoke, fire, sparking, a burning smell, heat at the panel, or any immediate danger?" },
      { speaker: "caller", text: "No, none of those." },
      { speaker: "assistant", text: "I'll mark this as an urgent issue for review. What is your name and service address?" },
      { speaker: "caller", text: "Alex Martin, 91 Lake Street in Grimsby." },
      { speaker: "assistant", text: "What is the best callback number?" },
      { speaker: "caller", text: "905-555-0160." },
      { speaker: "assistant", text: "I'll prepare the urgent request. I cannot guarantee dispatch or a response time, and the electrical team must confirm the next step." },
    ],
    collected: ["Alex Martin", "905-555-0160", "91 Lake Street · Grimsby", "Complete home outage", "Neighbours still have power", "No immediate-danger indicators reported"],
    missing: ["Preferred callback time"],
    summary: "PRIORITY — Alex reports a complete home outage while neighbouring properties still have power. No smoke, fire, sparks, burning smell, panel heat, or immediate danger was reported.",
    ownerText: "PRIORITY CALLBACK · Alex Martin · 905-555-0160 · Complete home outage · 91 Lake Street, Grimsby · No immediate-danger indicators reported.",
    customerText: "Thanks for calling Tim's Electrical. We recorded your urgent power-outage request. This is not a dispatch confirmation; the team must review the details and contact you.",
  },
  {
    id: "safety-redirect",
    shortLabel: "Safety redirect",
    title: "Caller reports smoke and sparks",
    intent: "Immediate-danger report",
    priority: "Emergency redirect",
    route: "911 · ordinary intake stopped",
    stages: ["Danger detected", "Intake stopped", "Emergency direction given", "Minimal event stored"],
    transcript: [
      { speaker: "caller", text: "There are sparks and smoke coming from an outlet." },
      { speaker: "assistant", text: "Leave the area and call 911 now from a safe location. Do not touch the outlet or wait for a service callback. This demonstration cannot provide emergency dispatch." },
    ],
    collected: ["Electrical sparks", "Smoke", "Emergency redirect issued"],
    missing: [],
    summary: "The caller reported sparks and smoke. Ordinary intake stopped immediately and the caller was directed to leave danger and call 911.",
    ownerText: "SAFETY EVENT · Caller reported sparks and smoke · Ordinary service intake stopped · Caller directed to leave danger and call 911.",
    customerText: "No routine confirmation text is prepared during an emergency redirect. The caller was directed to leave danger and call 911.",
  },
];
